COMMAND_PREFIX = '$'

GUILD_ID = 1140325411126005901 # Koutokomia
MEMBER_COUNT_CHANNEL_ID = 1192792733039996938
SYSTEM_CHANNEL_ID = 1140325411126005903 # ιντριγκα
FREE_GAMES_CHANNEL_ID = 1190706436683071648 # free-games

HELP_COMMAND = "$help"
REAL_NAME_COMMAND = "$real_name"
GREET_COMMAND = "$greet"
RETRIEVE_COMMAND = "$retrieve"
FACT_COMMAND = "$fact"
TZELO_COMMAND = "$tzelo"

AUDIO_DIR = "./audio"
WELCOME_FILE = "welcome.txt"
HELP_FILE ="help.txt"
FACTS_FILE = "facts.txt"
MAGIC_FILE = "magic_message.txt"

MEMBER_COUNT_CHANNEL_PREFIX = "Souls: "
MEMBER_COUNT_LOOP_SECONDS = 30
FREE_STR = "free"
FREE_GAMES_REACTION = "\U0001F42D"
ZERO = 0
ONE = 1
REAL_NAME_RESPONSE = "Claire Elise Boucher"
PLAYING_ACTIVITY = "NieR:Automata™"

GRIMES_STR = "grimes"
BUSINESS_INSIDER = "business-insider"
PUBLISHED_AT = "publishedAt"
ARTICLES = "articles"
TITLE = "title"
URL_STR = "url"